### ISSUE TITLE
Is there any requirement about the resolution of input image?

### ISSUE THREAD

**Issue by qiusuor** [InterDigitalInc/CompressAI#18]
When I tried to compress an image of 400*500 resolution using pre-traind  bmshj2018_hyperprior model, I got such error:
torch.Size([1, 3, 500, 400])

Traceback (most recent call last):
  File "compress_scale_img_val.py", line 139, in <module>
    out_net = net.forward(x)
  File "/home/super/CompressAI/compressai/models/priors.py", line 263, in forward
    y_hat, y_likelihoods = self.gaussian_conditional(y, scales_hat)
  File "/home/super/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/super/CompressAI/compressai/entropy_models/entropy_models.py", line 576, in forward
    likelihood = self._likelihood(outputs, scales, means)
  File "/home/super/CompressAI/compressai/entropy_models/entropy_models.py", line 565, in _likelihood
    upper = self._standardized_cumulative((half - values) / scales)
RuntimeError: The size of tensor a (25) must match the size of tensor b (28) at non-singleton dimension 3

**Comment by jbegaint** [comment]
yes, due to downsampling/stride operations the input images spatial dimensions need to be a multiple of 64 (for most models). Here's a padding/cropping example: https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/utils/eval_model/__main__.py#L77.
