### ISSUE TITLE
Testcase fails while creating PR

### ISSUE THREAD

**Issue by danishnazir** [InterDigitalInc/CompressAI#222]
## Bug

Hi, I want to create a Pull Request to enable DDP training in this repository. However, I am unable to pass the test cases. The stacktrace shows error regarding some `sqlite `operations, which I am not really sure how to interpret. Whats the connection of `sqlite `and the library itself? does it store some intermediate results there?

## To Reproduce

`python -m pytest --cov=compressai -s`

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1173, in _execute
INTERNALERROR>     return self.con.execute(sql, parameters)    # type: ignore[arg-type]
INTERNALERROR> sqlite3.OperationalError: no such table: coverage_schema
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1178, in _execute
INTERNALERROR>     return self.con.execute(sql, parameters)    # type: ignore[arg-type]
INTERNALERROR> sqlite3.OperationalError: no such table: coverage_schema
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 293, in _read_db
INTERNALERROR>     row = db.execute_one("select version from coverage_schema")
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1235, in execute_one
INTERNALERROR>     with self.execute(sql, parameters) as cur:
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/contextlib.py", line 113, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1207, in execute
INTERNALERROR>     cur = self._execute(sql, parameters)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1195, in _execute
INTERNALERROR>     raise DataError(f"Couldn't use data file {self.filename!r}: {msg}") from exc
INTERNALERROR> coverage.exceptions.DataError: Couldn't use data file '/mnt/batch/tasks/shared/LS_root/mounts/clusters/compressai-multigpu/code/Users/danish.nazir/CompressAI-DDP/.coverage.compressai-multigpu.41931.560935': no such table: coverage_schema
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pytest_cov/plugin.py", line 297, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pytest_cov/engine.py", line 242, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/control.py", line 755, in save
INTERNALERROR>     data = self.get_data()
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/control.py", line 835, in get_data
INTERNALERROR>     if self._collector.flush_data():
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/collector.py", line 499, in flush_data
INTERNALERROR>     self.covdata.add_lines(self.mapped_file_dict(line_data))
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 126, in _wrapped
INTERNALERROR>     return method(self, *args, **kwargs)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 492, in add_lines
INTERNALERROR>     self._choose_lines_or_arcs(lines=True)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 558, in _choose_lines_or_arcs
INTERNALERROR>     with self._connect() as con:
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 344, in _connect
INTERNALERROR>     self._open_db()
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 287, in _open_db
INTERNALERROR>     self._read_db()
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 297, in _read_db
INTERNALERROR>     self._init_db(db)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 326, in _init_db
INTERNALERROR>     db.executescript(SCHEMA)
INTERNALERROR>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/coverage/sqldata.py", line 1274, in executescript
INTERNALERROR>     self.con.executescript(script).close()
INTERNALERROR> sqlite3.OperationalError: database is locked

```

**Comment by YodaEmbedding** [comment]
Looks likehttps://github.com/pytest-dev/pytest-cov/issues/476

**Comment by YodaEmbedding** [comment]
Looks like an upstream problem with running coverage tests on Azure:

likehttps://github.com/pytest-dev/pytest-cov/issues/476

Recommendation: skip the coverage tests.
