### ISSUE TITLE
Image size=(672, 512) cannot be processed by most model

### ISSUE THREAD

**Issue by mynotwo** [InterDigitalInc/CompressAI#252]
Hi, I'm using your colab tutorial to compress some random size images. And I found  that when image size=(672, 512), they cannot be processed. Could you fix this bug?

**Comment by YodaEmbedding** [comment]
There are different ways to deal with this. One way is to pad the image until it is a multiple of 64.

**Comment by mynotwo** [comment]
> There are different ways to deal with this. One way is to pad the image until it is a multiple of 64.

But I want to compress the image. Wouldn't padding affect the compression ratio?

**Comment by YodaEmbedding** [comment]
I believe pre-padding before a transform is a necessary evil that even some (non-learned) codecs use, though I'm guessing they've become more efficient at it than they were historically. (Or perhaps not, since presumably, DFT/DCT/DWT of a zero-padded signal may have its effects mitigated through some properties of the transforms...)

## Worst-case test

Testing by padding an extra 64x64:

```python
import torch
import torch.nn.functional as F
from compressai.zoo import bmshj2018_hyperprior
from PIL import Image
from torchvision import transforms

device = "cuda"
net = bmshj2018_hyperprior(quality=2, pretrained=True).eval().to(device)
img = Image.open("/data/datasets/kodak/test/kodim01.png").convert("RGB")
x = transforms.ToTensor()(img).unsqueeze(0).to(device)

def inference(net, x):
    with torch.no_grad():
        out_enc = net.compress(x)
    [y_strings, z_strings] = out_enc["strings"]
    file_size = sum(len(s) for s in y_strings) + sum(len(s) for s in z_strings)
    return file_size

x_pad_a_lot = F.pad(x, (64, 64, 64, 64), mode="constant", value=0)
print(f"No pad:    {inference(net, x)} bytes")
print(f"With pad:  {inference(net, x_pad_a_lot)} bytes")
```

bmshj2018-hyperprior:
```
No pad:    16500 bytes
With pad:  17384 bytes
```

mbt2018:
```
No pad:   14680 bytes
With pad: 14976 bytes
```

Yes, it looks like there is a difference felt, particularly for entropy models that are "weaker" at spatial redundancy.

---

## Smart padding

Another method I've seen proposed by Huawei (IIRC) is to pad to a multiple of 2 (i.e. even dimensions) just before each 2x downsampling operation. But you'll need to intertwine these operations into the model layers. Perhaps define a `SmartPadding` layer:

```python
import torch.nn as nn
import torch.nn.functional as F
from compressai.ops import compute_padding

class SmartPadding(nn.Module):
    def __init__(self, min_div=2, mode="pad", link=None, **padding_kwargs):
        super().__init__()
        self.min_div = min_div
        self.padding_kwargs = padding_kwargs
        self.mode = mode
        self._unpad = None
        self._linked_modules = []
        if link is not None:
            self._linked_modules.append(link)

    def forward(self, x):
        *_, h, w = x.shape
        if self.mode == "pad":
            padding, self._unpad = compute_padding(h, w, self.min_div)
        elif self.mode == "unpad":
            padding = self._linked_modules[0]._unpad
        return F.pad(x, padding, **self.padding_kwargs)
```

And then define a method for injecting these layers into an existing model:

```python
def inject_model(self):
    # self.g_a = nn.Sequential(
    #     SmartPadding(),
    #     conv(3, N),
    #     GDN(N),
    #     SmartPadding(),
    #     conv(N, N),
    #     GDN(N),
    #     SmartPadding(),
    #     conv(N, N),
    #     GDN(N),
    #     SmartPadding(),
    #     conv(N, M),
    # )

    self.g_a.insert(0, SmartPadding())
    self.g_a.insert(3, SmartPadding())
    self.g_a.insert(6, SmartPadding())
    self.g_a.insert(9, SmartPadding())

    # self.g_s = nn.Sequential(
    #     deconv(M, N),
    #     SmartPadding(mode="unpad", link=self.g_a[9]),
    #     GDN(N, inverse=True),
    #     deconv(N, N),
    #     SmartPadding(mode="unpad", link=self.g_a[6]),
    #     GDN(N, inverse=True),
    #     deconv(N, N),
    #     SmartPadding(mode="unpad", link=self.g_a[3]),
    #     GDN(N, inverse=True),
    #     deconv(N, 3),
    #     SmartPadding(mode="unpad", link=self.g_a[0]),
    # )

    self.g_s.insert(1, SmartPadding(mode="unpad", link=self.g_a[9]))
    self.g_s.insert(4, SmartPadding(mode="unpad", link=self.g_a[6]))
    self.g_s.insert(7, SmartPadding(mode="unpad", link=self.g_a[3]))
    self.g_s.insert(10, SmartPadding(mode="unpad", link=self.g_a[0]))

    # self.h_a = nn.Sequential(
    #     conv(M, N, stride=1, kernel_size=3),
    #     nn.ReLU(inplace=True),
    #     SmartPadding(),
    #     conv(N, N),
    #     nn.ReLU(inplace=True),
    #     SmartPadding(),
    #     conv(N, N),
    # )

    self.h_a.insert(2, SmartPadding())
    self.h_a.insert(5, SmartPadding())

    # self.h_s = nn.Sequential(
    #     deconv(N, N),
    #     SmartPadding(mode="unpad", link=self.h_a[5]),
    #     nn.ReLU(inplace=True),
    #     deconv(N, N),
    #     SmartPadding(mode="unpad", link=self.h_a[2]),
    #     nn.ReLU(inplace=True),
    #     conv(N, M, stride=1, kernel_size=3),
    #     nn.ReLU(inplace=True),
    # )

    self.h_s.insert(1, SmartPadding(mode="unpad", link=self.h_a[5]))
    self.h_s.insert(4, SmartPadding(mode="unpad", link=self.h_a[2]))
```

...And finally, let's inject and compare the various methods:

```python
import torch
import torch.nn.functional as F
from compressai.zoo import bmshj2018_hyperprior
from PIL import Image
from torchvision import transforms

device = "cuda"
net = bmshj2018_hyperprior(quality=2, pretrained=True).eval().to(device)
img = Image.open("/data/datasets/kodak/test/kodim01.png").convert("RGB")
x = transforms.ToTensor()(img).unsqueeze(0).to(device)

def inference(net, x):
    with torch.no_grad():
        out_enc = net.compress(x)
    [y_strings, z_strings] = out_enc["strings"]
    file_size = sum(len(s) for s in y_strings) + sum(len(s) for s in z_strings)
    return file_size

x_pad_a_bit = F.pad(x, (1, 1, 1, 1), mode="constant", value=0)
x_pad_a_lot = F.pad(x, (64, 64, 64, 64), mode="constant", value=0)
print(f"No pad:    {inference(net, x)} bytes")
print(f"With pad:  {inference(net, x_pad_a_lot)} bytes")
inject_model(net)
print(f"Smart pad: {inference(net, x_pad_a_bit)} bytes")
```

Output:

```
No pad:    16500 bytes
With pad:  17384 bytes
Smart pad: 17444 bytes
```

...Hmm... it's not as good as I had hoped, but this was without any special training. We're padding tensors with zeroes, and hoping it doesn't alter their behavior too much, after all. Perhaps better models that are padding-adaptive could be trained.

**Comment by WenBingo** [comment]
> Hi, I'm using your colab tutorial to compress some random size images. And I found that when image size=(672, 512), they cannot be processed. Could you fix this bug?

Hello, I would like to ask you a question about the installation of compressai “Successfully installed compressai-1.2.4.dev0” . I successfully installed cmpressai, but I got the following error when importing:

>>> import compressai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\compressai\compressai\__init__.py", line 30, in <module>
    from compressai import (
  File "F:\compressai\compressai\latent_codecs\__init__.py", line 38, in <module>
    from .rasterscan import RasterScanLatentCodec
  File "F:\compressai\compressai\latent_codecs\rasterscan.py", line 38, in <module>
    from compressai.ans import BufferedRansEncoder, RansDecoder
ImportError: DLL load failed while importing ans: 找不到指定的程序。
