### ISSUE TITLE
ModuleNotFoundError: No module named 'compressai._CXX'

### ISSUE THREAD

**Issue by OzanKara41** [InterDigitalInc/CompressAI#26]
I am getting this error : ModuleNotFoundError: No module named 'compressai._CXX' 

Thanks from now.

**Comment by jbegaint** [comment]
Hi, thanks for the report. This error indicates that the c++ module extension is missing.
What's the output of `pip install ./compressai` on your environment?

**Comment by OzanKara41** [comment]
Thans for reply. When i write `pip install ./compressai`, the output like this:

![torch_!](https://user-images.githubusercontent.com/56604093/106522755-34c2a700-64f1-11eb-909c-236c4bd68279.PNG)

**Comment by jbegaint** [comment]
this seems related to your pytorch installation. Maybe try to re-install torch following https://pytorch.org/get-started/locally/

**Comment by OzanKara41** [comment]
I have re-installed Pytorch 1.7.1 but the problem still persists. Sorry for delay. Thanks.
![hata4](https://user-images.githubusercontent.com/56604093/107547687-c52e7500-6bde-11eb-9d35-32393e5d7334.PNG)

**Comment by jbegaint** [comment]
can you paste the full log here or in a gist?
thanks

**Comment by OzanKara41** [comment]
(torch_env) C:\Users\akaraca>pip install ./compressai
Processing c:\users\akaraca\compressai
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from compressai==1.1.0) (1.19.2)
Requirement already satisfied: scipy in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from compressai==1.1.0) (1.6.0)
Requirement already satisfied: torchvision>=0.5.0 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from compressai==1.1.0) (0.8.2)
Requirement already satisfied: torch>=1.4.0 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from compressai==1.1.0) (1.7.1)
Collecting pytorch-msssim==0.2.0
  Using cached pytorch_msssim-0.2.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from compressai==1.1.0) (3.3.4)
Requirement already satisfied: typing_extensions in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from torch>=1.4.0->compressai==1.1.0) (3.7.4.3)
Requirement already satisfied: pillow>=4.1.1 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from torchvision>=0.5.0->compressai==1.1.0) (8.1.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from matplotlib->compressai==1.1.0) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from matplotlib->compressai==1.1.0) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from matplotlib->compressai==1.1.0) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from matplotlib->compressai==1.1.0) (2.4.7)
Requirement already satisfied: six in c:\programdata\anaconda3\envs\torch_env\lib\site-packages (from cycler>=0.10->matplotlib->compressai==1.1.0) (1.15.0)
Building wheels for collected packages: compressai
  Building wheel for compressai (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\envs\torch_env\python.exe' 'c:\programdata\anaconda3\envs\torch_env\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\akaraca\AppData\Local\Temp\tmpqdrz5_sh'
       cwd: C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb
  Complete output (145 lines):
  No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\compressai
  copying compressai\version.py -> build\lib.win-amd64-3.7\compressai
  copying compressai\__init__.py -> build\lib.win-amd64-3.7\compressai
  creating build\lib.win-amd64-3.7\compressai\datasets
  copying compressai\datasets\utils.py -> build\lib.win-amd64-3.7\compressai\datasets
  copying compressai\datasets\__init__.py -> build\lib.win-amd64-3.7\compressai\datasets
  creating build\lib.win-amd64-3.7\compressai\entropy_models
  copying compressai\entropy_models\entropy_models.py -> build\lib.win-amd64-3.7\compressai\entropy_models
  copying compressai\entropy_models\__init__.py -> build\lib.win-amd64-3.7\compressai\entropy_models
  creating build\lib.win-amd64-3.7\compressai\layers
  copying compressai\layers\gdn.py -> build\lib.win-amd64-3.7\compressai\layers
  copying compressai\layers\layers.py -> build\lib.win-amd64-3.7\compressai\layers
  copying compressai\layers\__init__.py -> build\lib.win-amd64-3.7\compressai\layers
  creating build\lib.win-amd64-3.7\compressai\models
  copying compressai\models\priors.py -> build\lib.win-amd64-3.7\compressai\models
  copying compressai\models\utils.py -> build\lib.win-amd64-3.7\compressai\models
  copying compressai\models\waseda.py -> build\lib.win-amd64-3.7\compressai\models
  copying compressai\models\__init__.py -> build\lib.win-amd64-3.7\compressai\models
  creating build\lib.win-amd64-3.7\compressai\ops
  copying compressai\ops\bound_ops.py -> build\lib.win-amd64-3.7\compressai\ops
  copying compressai\ops\ops.py -> build\lib.win-amd64-3.7\compressai\ops
  copying compressai\ops\parametrizers.py -> build\lib.win-amd64-3.7\compressai\ops
  copying compressai\ops\__init__.py -> build\lib.win-amd64-3.7\compressai\ops
  creating build\lib.win-amd64-3.7\compressai\transforms
  copying compressai\transforms\functional.py -> build\lib.win-amd64-3.7\compressai\transforms
  copying compressai\transforms\transforms.py -> build\lib.win-amd64-3.7\compressai\transforms
  copying compressai\transforms\__init__.py -> build\lib.win-amd64-3.7\compressai\transforms
  creating build\lib.win-amd64-3.7\compressai\utils
  copying compressai\utils\__init__.py -> build\lib.win-amd64-3.7\compressai\utils
  creating build\lib.win-amd64-3.7\compressai\zoo
  copying compressai\zoo\image.py -> build\lib.win-amd64-3.7\compressai\zoo
  copying compressai\zoo\pretrained.py -> build\lib.win-amd64-3.7\compressai\zoo
  copying compressai\zoo\__init__.py -> build\lib.win-amd64-3.7\compressai\zoo
  creating build\lib.win-amd64-3.7\compressai\utils\bench
  copying compressai\utils\bench\codecs.py -> build\lib.win-amd64-3.7\compressai\utils\bench
  copying compressai\utils\bench\__init__.py -> build\lib.win-amd64-3.7\compressai\utils\bench
  copying compressai\utils\bench\__main__.py -> build\lib.win-amd64-3.7\compressai\utils\bench
  creating build\lib.win-amd64-3.7\compressai\utils\eval_model
  copying compressai\utils\eval_model\__init__.py -> build\lib.win-amd64-3.7\compressai\utils\eval_model
  copying compressai\utils\eval_model\__main__.py -> build\lib.win-amd64-3.7\compressai\utils\eval_model
  creating build\lib.win-amd64-3.7\compressai\utils\find_close
  copying compressai\utils\find_close\__init__.py -> build\lib.win-amd64-3.7\compressai\utils\find_close
  copying compressai\utils\find_close\__main__.py -> build\lib.win-amd64-3.7\compressai\utils\find_close
  creating build\lib.win-amd64-3.7\compressai\utils\plot
  copying compressai\utils\plot\__init__.py -> build\lib.win-amd64-3.7\compressai\utils\plot
  copying compressai\utils\plot\__main__.py -> build\lib.win-amd64-3.7\compressai\utils\plot
  creating build\lib.win-amd64-3.7\compressai\utils\update_model
  copying compressai\utils\update_model\__init__.py -> build\lib.win-amd64-3.7\compressai\utils\update_model
  copying compressai\utils\update_model\__main__.py -> build\lib.win-amd64-3.7\compressai\utils\update_model
  running build_ext
  building 'compressai.ans' extension
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts
  creating C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans
  Emitting ninja build file C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl.exe: [WinError 2] Sistem belirtilen dosyayı bulamıyor
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
  [1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\third_party\ryg_rans -IC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\TH -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\THC -Ic:\programdata\anaconda3\envs\torch_env\include -Ic:\programdata\anaconda3\envs\torch_env\include -c C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans\rans_interface.cpp /FoC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans\rans_interface.obj -std=c++17 -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ans -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
  FAILED: C:/Users/akaraca/AppData/Local/Temp/pip-req-build-xtrasshb/build/temp.win-amd64-3.7/Release/Users/akaraca/AppData/Local/Temp/pip-req-build-xtrasshb/compressai/cpp_exts/rans/rans_interface.obj
  cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\third_party\ryg_rans -IC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\TH -IC:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\include\THC -Ic:\programdata\anaconda3\envs\torch_env\include -Ic:\programdata\anaconda3\envs\torch_env\include -c C:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans\rans_interface.cpp /FoC:\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\build\temp.win-amd64-3.7\Release\Users\akaraca\AppData\Local\Temp\pip-req-build-xtrasshb\compressai\cpp_exts\rans\rans_interface.obj -std=c++17 -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ans -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
  CreateProcess failed: The system cannot find the file specified.
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
      env=env)
    File "c:\programdata\anaconda3\envs\torch_env\lib\subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "c:\programdata\anaconda3\envs\torch_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\programdata\anaconda3\envs\torch_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\programdata\anaconda3\envs\torch_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\build_meta.py", line 217, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 136, in <module>
      "build_ext": BuildExtension,
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
      build_ext.build_extensions(self)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "c:\programdata\anaconda3\envs\torch_env\lib\distutils\command\build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
      with_cuda=with_cuda)
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "C:\Users\akaraca\AppData\Local\Temp\pip-build-env-6d8f4ril\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for compressai
Failed to build compressai
ERROR: Could not build wheels for compressai which use PEP 517 and cannot be installed directly

**Comment by jbegaint** [comment]
` subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`
looks like `ninja` is not installed on your machine

**Comment by jbegaint** [comment]
according to `https://pytorch.org/docs/stable/cpp_extension.html`, it should fall back on the default distutils if `ninja` is not installed.

**Comment by OzanKara41** [comment]
I tried to install ninja but i am getting  diffrent error. Could this error be due to visualstudio ?
![soru3_1](https://user-images.githubusercontent.com/56604093/107550187-c3b27c00-6be1-11eb-8f89-4de749830e16.PNG)
![soru3_2](https://user-images.githubusercontent.com/56604093/107550200-c7de9980-6be1-11eb-8758-eee41a6bd898.PNG)

**Comment by jbegaint** [comment]
Hum, I'm not familiar with the windows ecosystem. Actually we don't test on windows.
We are looking at publishing pre-build packages soon. You could also use a docker linux image in the meantime.

**Comment by OzanKara41** [comment]
Thank's a lot for your help. I will try.

**Comment by Sagar-Panchal-Sagar** [comment]
> Hi, thanks for the report. This error indicates that the c++ module extension is missing. What's the output of `pip install ./compressai` on your environment?

![Screenshot (193)](https://github.com/InterDigitalInc/CompressAI/assets/150721435/1284c62f-1a3a-4bf7-928f-66a3a313333b)


I am getting this output of the above command. I have already installed compressai but I am still getting this error. Could you please help? @jbegaint

**Comment by Xer-GWX** [comment]
Hi, I have the same problem with you. Have you solved it?
