### ISSUE TITLE
Does CompressAI support direct compression of [y] instead of [y-mean]?

### ISSUE THREAD

**Issue by zhengxinChenee** [InterDigitalInc/CompressAI#262]
As stated, how can we use CompressAI to compress [y] instead of [y-mean]. Furthermore, how can we understand the advantages of compressing [y-mean]? Thank you very much for your answer!!!

**Comment by YodaEmbedding** [comment]
`round(y-means) == round(y)` if `means = 0`.  (Or `means == None` works too.)

For example, just set `means=None` when using the desired entropy model:

```python
        y_hat, y_likelihoods = self.gaussian_conditional(y, scales_hat, means=means_hat)
```

---

In terms of advantages, that depends on the situation. If the source `y` has its most-likely-value occurring exactly at the mean, then `[y - mean]` will probably produce less reconstruction error since we can then reconstruct the most-likely-value with exact precision. On the other hand, if the actual values occur at locations other than the `mean`, then both methods will produce similar results. So... it depends.

---

Somewhat related concept: the deadzone quantizer used by JPEG allows near-zero DCT-transformed-and-[rescaled](https://www.google.com/search?q=JPEG+quantization+table) coefficients to be rounded to zero, which helps reduce the rate since the most-likely-symbols are near zero, and reconstructing them as zero is worth the R-D tradeoff.

![deadzone](https://github.com/InterDigitalInc/CompressAI/assets/721196/a0414146-53a3-43e8-bde0-42ad3ad7bc15)

**Comment by zhengxinChenee** [comment]
Great answer! Thanks a lot! In general, compressing [y-mean] achieves better R-D tradeoff. However, in some cases, we have to compress [y] whose mean is not none. For example, in Checkerboard Context Model, we should compress [y] for one-pass encoding, and compressing [y-mean] leads to two-pass encoding. Can you make some suggestions for AE/AD of [y] using CompressAI?Thank you very much for your answer!!!

**Comment by WenBingo** [comment]
> As stated, how can we use CompressAI to compress [y] instead of [y-mean]. Furthermore, how can we understand the advantages of compressing [y-mean]? Thank you very much for your answer!!!

Hello, I would like to ask you a question about the installation of compressai “Successfully installed compressai-1.2.4.dev0” . I successfully installed cmpressai, but I got the following error when importing:

>>> import compressai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\compressai\compressai\__init__.py", line 30, in <module>
    from compressai import (
  File "F:\compressai\compressai\latent_codecs\__init__.py", line 38, in <module>
    from .rasterscan import RasterScanLatentCodec
  File "F:\compressai\compressai\latent_codecs\rasterscan.py", line 38, in <module>
    from compressai.ans import BufferedRansEncoder, RansDecoder
ImportError: DLL load failed while importing ans: 找不到指定的程序。
