### ISSUE TITLE
No detailed description of the API compress.ans found

### ISSUE THREAD

**Issue by GraceZhuuu** [InterDigitalInc/CompressAI#271]
## Documentation

There are no  `parameters` or `source` in documentation(https://interdigitalinc.github.io/CompressAI/ans.html) 
Where I can find that, 3Q.

**Comment by WenBingo** [comment]
> ## Documentation
> There are no `parameters` or `source` in documentation(https://interdigitalinc.github.io/CompressAI/ans.html) Where I can find that, 3Q.

Hello, I would like to ask you a question about the installation of compressai “Successfully installed compressai-1.2.4.dev0” . I successfully installed cmpressai, but I got the following error when importing:

>>> import compressai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\compressai\compressai\__init__.py", line 30, in <module>
    from compressai import (
  File "F:\compressai\compressai\latent_codecs\__init__.py", line 38, in <module>
    from .rasterscan import RasterScanLatentCodec
  File "F:\compressai\compressai\latent_codecs\rasterscan.py", line 38, in <module>
    from compressai.ans import BufferedRansEncoder, RansDecoder
ImportError: DLL load failed while importing ans: 找不到指定的程序。

**Comment by GraceZhuuu** [comment]
> > ## Documentation
> > There are no `parameters` or `source` in documentation(https://interdigitalinc.github.io/CompressAI/ans.html) Where I can find that, 3Q.
> 
> Hello, I would like to ask you a question about the installation of compressai “Successfully installed compressai-1.2.4.dev0” . I successfully installed cmpressai, but I got the following error when importing:
> 
> > > > import compressai
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "F:\compressai\compressai__init__.py", line 30, in 
> > > > from compressai import (
> > > > File "F:\compressai\compressai\latent_codecs__init__.py", line 38, in 
> > > > from .rasterscan import RasterScanLatentCodec
> > > > File "F:\compressai\compressai\latent_codecs\rasterscan.py", line 38, in 
> > > > from compressai.ans import BufferedRansEncoder, RansDecoder
> > > > ImportError: DLL load failed while importing ans: 找不到指定的程序。

If you have unrelated questions, please open a new issue to ask.

**Comment by YodaEmbedding** [comment]
The source code is here:

https://github.com/InterDigitalInc/CompressAI/tree/master/compressai/cpp_exts/rans

Pybind11 binds these C++ functions to Python.
