### ISSUE TITLE
ImportError: DLL load failed while importing ans:

### ISSUE THREAD

**Issue by WenBingo** [InterDigitalInc/CompressAI#273]
Hello, I would like to ask you a question about the installation of compressai “Successfully installed compressai-1.2.4.dev0” . I successfully installed cmpressai, but I got the following error when importing:

>>> import compressai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\compressai\compressai\__init__.py", line 30, in <module>
    from compressai import (
  File "F:\compressai\compressai\latent_codecs\__init__.py", line 38, in <module>
    from .rasterscan import RasterScanLatentCodec
  File "F:\compressai\compressai\latent_codecs\rasterscan.py", line 38, in <module>
    from compressai.ans import BufferedRansEncoder, RansDecoder
ImportError: DLL load failed while importing ans: 找不到指定的程序。

**Comment by fracape** [comment]
Hi, this could be due to the merge of the PR on GMM using cpp torch extensions. This needed to be handled with care as the build needs to match cuda / python used to build torch. I reverted to a classical use of pybind of the ANS cpp extension as we provide compressai as a package and it's complicated to support all versions. Please pull the current master or tag 1.2.5 and re-install. Let me know if the problem persist and please provide your environment as detailed in the template issue.
