### ISSUE TITLE
error when trying to use entropy bottleneck of compressai in my code

### ISSUE THREAD

**Issue by takhtardeshirsoheib** [InterDigitalInc/CompressAI#297]
error as below:

 python train.py 
Traceback (most recent call last):
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\train.py", line 165, in <module>
    main()
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\train.py", line 41, in main
    model = CombinedVAE(latent_channels=latent_channels, pre_trained_spatial_path='./Spatial_checkpoints/vae_model_FT_epoch_200.pth')
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\model.py", line 13, in __init__
    self.entropy_bottleneck = EntropyBottleneck(latent_channels_s)
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\compressai\compressai\entropy_models\entropy_models.py", line 351, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\compressai\compressai\entropy_models\entropy_models.py", line 118, in __init__
    entropy_coder = default_entropy_coder()
  File "C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\compressai\compressai\entropy_models\entropy_models.py", line 84, in default_entropy_coder
    from compressai import get_entropy_coder
ImportError: cannot import name 'get_entropy_coder' from 'compressai' (unknown location)

**Comment by YodaEmbedding** [comment]
That says `compressai` is not available in Python's paths.

Try one of the following:

 - Install CompressAI using the instructions in https://github.com/InterDigitalInc/CompressAI?tab=readme-ov-file#installation. In your case, this means creating a virtual environment, activating the virtual environment, and then `pip install -e C:\Users\sohtak\Ph.D-Sweden-France\Sweden\Phase2\Python-Codes\The_Final_versions\VAE_05062024_Bestversion\compressai`.

Note that CompressAI is not officially supported on Windows. However, some users have figured out how to get it running by installing the relevant compilers.
