### ISSUE TITLE
Error while encoding yuv video 

### ISSUE THREAD

**Issue by gopi77** [InterDigitalInc/CompressAI#321]
## Bug
Got the below error while encoding a yuv sequence. 

PS D:\project\video_coding\test> python3 D:\project\video_coding\compressai\examples\codec.py encode D:\project\video_coding\test\KristenAndSara_1280x720_60Hz_8bit.yuv -f 60
Traceback (most recent call last):
  File "D:\project\video_coding\compressai\examples\codec.py", line 603, in <module>
    main(sys.argv[1:])
  File "D:\project\video_coding\compressai\examples\codec.py", line 597, in main
    encode(argv)
  File "D:\project\video_coding\compressai\examples\codec.py", line 555, in encode
    _encode(
  File "D:\project\video_coding\compressai\examples\codec.py", line 381, in _encode
    out = encode_func[codec_type](input, codec_info, output)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\video_coding\compressai\examples\codec.py", line 258, in encode_image
    org_seq = RawVideoSequence.from_file(input)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\video_coding\compressai\compressai\datasets\rawvideo.py", line 292, in from_file
    info = get_raw_video_file_info(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\video_coding\compressai\compressai\datasets\rawvideo.py", line 169, in get_raw_video_file_info
    if info["bitdepth"] and info["bitdepth2"] and info["bitdepth"] != info["bitdepth2"]:
                            ~~~~^^^^^^^^^^^^^
KeyError: 'bitdepth2'


<!-- A clear and concise description of what the bug is. -->

## To Reproduce

Steps to reproduce the behavior:

1. Run the above command in windows PowerShell

<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Environment

Please copy and paste the output from `python3 -m torch.utils.collect_env`

PyTorch version: 2.2.2+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.31.1
Libc version: N/A

Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 560.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=4001
DeviceID=CPU0
Family=198
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=4001
Name=Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
ProcessorType=3
Revision=24067

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-msssim==1.0.0
[pip3] torch==2.2.2
[pip3] torch-geometric==2.6.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.17.2
[conda] Could not collect

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by gopi77** [comment]
Updated the input file name and its working
The command with updated filename: codec.py  encode .\KristenAndSara_1280x720_60Hz_8bit_P420.yuv -f 60 --model ssf2020
