### ISSUE TITLE
Evaluation Script

### ISSUE THREAD

**Issue by PascalBACCHUS** [InterDigitalInc/CompressAI#39]
Hello,

First of all, thank you for your work.

I trained a model (bmshj2018-factorized) on my own dataset and then tried to do some tests with your evaluation script.

I used train.py, exactly as you recommend in Readme.md or in Issue 32 (now closed).
python3 train.py -d $DATASET --epochs 300 -lr 1e-4 --batch-size 16 --cuda --save

Then,
python3 -m compressai.utils.eval_model checkpoint /path/to/images/folder/ -a bmshj2018-factorized -p checkpoint.pth.tar

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 301, in <module>
    main(sys.argv[1:])
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 277, in main
    model = load_func(*opts, run)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 145, in load_checkpoint
    return architectures[arch].from_state_dict(torch.load(checkpoint_path)).eval()
  File "/udd/dbacchus/Codes/CompressAI/compressai/models/priors.py", line 165, in from_state_dict
    N = state_dict["g_a.0.weight"].size(0)
KeyError: 'g_a.0.weight'

This is the same error message as in Issue 22 but I don't understand the cause here as I'm not training a toy example not defined in the reference CompressAI models.

When I run,
print(torch.load("checkpoint_best_loss.pth.tar").keys())

I get,
dict_keys(['epoch', 'state_dict', 'loss', 'optimizer', 'aux_optimizer', 'lr_scheduler'])

Thank you.

**Comment by jbegaint** [comment]
Hi Pascal, right the format it a bit different, the evaluation expects just the state dict whereas the training script also saves training information (loss value, optimizer state, etc..) as you can see from the print. I'll update the evaluation script to accept checkpoints from the training script. In the mean time, it should work if you extract the `state_dict` key in the checkpoint from the train example.

**Comment by PascalBACCHUS** [comment]
Hi Jean,

Thank you for your reply.
I extracted the `state_dict` key from the checkpoint and feed it to `compressai.utils.eval_model`. However, I still have some errors while running it:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 301, in <module>
    main(sys.argv[1:])
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 280, in main
    metrics = eval_model(model, filepaths, args.entropy_estimation, args.half)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 157, in eval_model
    rv = inference(model, x)
  File "/udd/dbacchus/env_py3.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 93, in inference
    out_enc = model.compress(x_padded)
  File "/udd/dbacchus/Codes/CompressAI/compressai/models/priors.py", line 173, in compress
    y_strings = self.entropy_bottleneck.compress(y)
  File "/udd/dbacchus/Codes/CompressAI/compressai/entropy_models/entropy_models.py", line 461, in compress
    return super().compress(x, indexes, medians)
  File "/udd/dbacchus/Codes/CompressAI/compressai/entropy_models/entropy_models.py", line 218, in compress
    self._check_cdf_size()
  File "/udd/dbacchus/Codes/CompressAI/compressai/entropy_models/entropy_models.py", line 182, in _check_cdf_size
    raise ValueError("Uninitialized CDFs. Run update() first")
ValueError: Uninitialized CDFs. Run update() first
```

I decided to check the `state_dict` keys and compare them with the dictionary from your pre-trained models (same model and quality)
[https://compressai.s3.amazonaws.com/models/v1/bmshj2018-factorized-prior-3-5c6f152b.pth.tar](url)
I found some differences, especially in the item's order.

Finally, I tried to use this downloaded _tar_ file to test `compressai.utils.eval_model` just for the sake of running it and I got an error too.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 301, in <module>
    main(sys.argv[1:])
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 277, in main
    model = load_func(*opts, run)
  File "/udd/dbacchus/Codes/CompressAI/compressai/utils/eval_model/__main__.py", line 145, in load_checkpoint
    return architectures[arch].from_state_dict(torch.load(checkpoint_path)).eval()
  File "/udd/dbacchus/Codes/CompressAI/compressai/models/priors.py", line 168, in from_state_dict
    net.load_state_dict(state_dict)
  File "/udd/dbacchus/Codes/CompressAI/compressai/models/priors.py", line 105, in load_state_dict
    super().load_state_dict(state_dict)
  File "/udd/dbacchus/env_py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FactorizedPrior:
	Missing key(s) in state_dict: "entropy_bottleneck._matrix0", "entropy_bottleneck._bias0", "entropy_bottleneck._factor0", "entropy_bottleneck._matrix1", "entropy_bottleneck._bias1", "entropy_bottleneck._factor1", "entropy_bottleneck._matrix2", "entropy_bottleneck._bias2", "entropy_bottleneck._factor2", "entropy_bottleneck._matrix3", "entropy_bottleneck._bias3", "entropy_bottleneck._factor3", "entropy_bottleneck._matrix4", "entropy_bottleneck._bias4". 
	Unexpected key(s) in state_dict: "entropy_bottleneck._biases.0", "entropy_bottleneck._biases.1", "entropy_bottleneck._biases.2", "entropy_bottleneck._biases.3", "entropy_bottleneck._biases.4", "entropy_bottleneck._factors.0", "entropy_bottleneck._factors.1", "entropy_bottleneck._factors.2", "entropy_bottleneck._factors.3", "entropy_bottleneck._matrices.0", "entropy_bottleneck._matrices.1", "entropy_bottleneck._matrices.2", "entropy_bottleneck._matrices.3", "entropy_bottleneck._matrices.4".
```

**Comment by jbegaint** [comment]
Yes you need to update the model to compute the CDFs based on the trained parameters of the entropy bottleneck(s) (as per the doc here: https://interdigitalinc.github.io/CompressAI/tutorial_train.html#updating-the-model).

Regarding the error from the pretrained model, can you please provide the compressai version you are using?

**Comment by PascalBACCHUS** [comment]
I'm using the latest version v1.1.1.

**Comment by jbegaint** [comment]
ok thx, can you provide a short script so I can reproduce the error?

**Comment by PascalBACCHUS** [comment]
OK sure, it's quite simple really.

I just trained a model (bmshj2018-factorized) on my own dataset.
`python3 train.py -d $DATASET --epochs 100 -lr 1e-4 --batch-size 16 --cuda --save`

Then I downloaded a pretrained tar file as indicated in the documentation. 
[https://compressai.s3.amazonaws.com/models/v1/bmshj2018-factorized-prior-3-5c6f152b.pth.tar](url)

Finally I tried to run the `compressai.utils.eval_model` script
`python3 -m compressai.utils.eval_model checkpoint $DATASET -a bmshj2018-factorized -p bmshj2018-factorized-prior-3-5c6f152b.pth.tar`

**Comment by jbegaint** [comment]
Got it thanks!
So we changed the state dict format a few months ago to support multi gpu. Thanks for reporting this, we should convert the models in both `checkpoint` and `pretrained` mode.
 
Side note, you actually don't have to download manually the pretrained weights but can use this command `python3 -m compressai.utils.eval_model pretrained ...`

**Comment by PascalBACCHUS** [comment]
Glad to have been of use.

**Comment by zjnlxk** [comment]
I also encountered the same error, can you explain how to solve it?

**Comment by zjnlxk** [comment]
@jbegaint @PascalBACCHUS
