### ISSUE TITLE
Unable to evaluate my own model

### ISSUE THREAD

**Issue by JifanYin** [InterDigitalInc/CompressAI#49]
Thank you for your impressive work. I have a question when training my own model. I simply test the training codes:
`python3 examples/train.py -d ./DIV2K/ --epochs 5 -lr 1e-4 --batch-size 16 --cuda --save`

Then I evaluate my result by running:
`python -m compressai.utils.eval_model checkpoint ./DIV2K/test/ -a bmshj2018-factorized -p checkpoint_best_loss.pth.tar`

It returns the following error:
`Traceback (most recent call last):
  File "/home/jifan/anaconda3/envs/CAI/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jifan/anaconda3/envs/CAI/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jifan/CAI/CompressAI/compressai/utils/eval_model/__main__.py", line 309, in <module>
    main(sys.argv[1:])
  File "/home/jifan/CAI/CompressAI/compressai/utils/eval_model/__main__.py", line 285, in main
    model = load_func(*opts, run)
  File "/home/jifan/CAI/CompressAI/compressai/utils/eval_model/__main__.py", line 149, in load_checkpoint
    return architectures[arch].from_state_dict(state_dict).eval()
  File "/home/jifan/CAI/CompressAI/compressai/models/priors.py", line 161, in from_state_dict
    N = state_dict["g_a.0.weight"].size(0)
KeyError: 'g_a.0.weight'`

Python: 3.6.13
CompressAI: 1.1.5.dev0
Thanks!

**Comment by jbegaint** [comment]
Hi, you need to run `compressai.utils.update_model` first on your training checkpoint. I'll update the doc first to make this more clear.

**Comment by JifanYin** [comment]
Thank you for your reply! I realized that I overlooked the update of entropy bottlenecks' parameters. I'm going to use compressai.utils.update_model before evaluation, and will try another method: update entropybottleneck before save, and load checkpoint without update.

**Comment by jbegaint** [comment]
Great :-). Just be sure to use a torch state_dict for the evaluation script, the checkpoints saved by the training script contain additional information (https://github.com/InterDigitalInc/CompressAI/blob/master/examples/train.py#L342).
Feel free to reopen if you encounter any issues.
